### ISSUE TITLE
 Bubble sort

### ISSUE THREAD

**Issue by PPatrick-star** [PPatrick-star/Algorithm_std#1]
- One of the sorting algorithms, bubble sort
- Let's study bubble sort 
- And make to code

**Comment by PPatrick-star** [comment]
- pros/ cons
   -  구현이 간단
   -  하나의 요소가 끝에서 끝으로 이동하기 위해서는 배열의 모든요소들과 비교(교환) 되어야한다

**Comment by PPatrick-star** [comment]
# To code
## Pseudo code
- 배열이 있음(원소 수 무관)
- 배열의 첫번째에 위치한 수 꺼내기
- 배열의 두번째에 위치한 수 꺼내기
- 비교하기
- 앞의 수가 클경우 위치 교환 
- 아닐경우 유지
- 배열의 두번째 에 위치한 수 꺼내기
- 배열의 세번째에 위치한 수 꺼내기
- 비교
- 클경우 교환/ 작을경우 유지
- 반복

**Comment by Ryutt** [comment]
Move to https://github.com/PPatrick-star/Algorithm_std/issues/3
## 알고리즘에 사용할 배열 만들기
- int 형 배열을 수기 입력없이 배열의 크기만 입력 후 자동생성되도록 작성

- 배열 사이즈 지정
- Math.random() 이나 Random 을 사용하여 난수 생성
- 양수만 사용할 계획
- 생성된 난수의 사이즈 지정
- 생성된 난수의중복 방지 방안 고려
